version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "8000:8000"
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # RabbitMQ Management Console (optional)
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  app:
    build: .
    container_name: captive-portal
    restart: no
    depends_on:
      - rabbitmq
    ports:
      - "5000:5000"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    command: ["/wait-for-it.sh", "rabbitmq:5672", "--timeout=60", "--", "python", "run.py"]

